### PR TITLE
lower build requirements for rhel

### PR DESCRIPTION
**Pull request by xambroz**
Please consider lowering the requirements to allow build on RHEL.

### CODE REVIEW

**Comment by joachimmetz** [comment]
Why not use the distribution package instead ? Also see https://github.com/libyal/libcdata/wiki/Building#read-first

you don't need autotools to build a release only HEAD (development release)

**Comment by joachimmetz** [comment]
No input for reporter closing until more context is provided.

**Comment by xambroz** [comment]
> Why not use the distribution package instead ? Also see https://github.com/libyal/libcdata/wiki/Building#read-first
> you don't need autotools to build a release only HEAD (development release)

Using the git snapshot gives me the freedom to use certain point in time even before the release.
I am doing it like that before you even added the support for the spec files and before you started tagging releases.

**Comment by joachimmetz** [comment]
git is a [version control management system](https://en.wikipedia.org/wiki/Version_control) not a source distribution system. Lowering these values might reintroduce issues that have been addressed in later versions of autotools.

> I am doing it like that before you even added the support for the spec files and before you started tagging releases.

I don't understand this claim, wasn't the spec file was added on the initial commit ?

**Pull request closed without merging**
